[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
startCommand = "npm start"

[build.nixpacks]
buildCmd = "npm run build || true"
startCmd = "npm start"
